apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Chart.Name }}
spec:
  instances: 1

  storage:
    size: 5Gi

  # Resource requests and limits for the PostgreSQL pod
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.5"

  bootstrap:
    initdb:
      database: streamrecord
      owner: streamuser
      secret:
        name: {{ .Chart.Name }}-secret