apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  annotations:
  "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
stringData:
  username: streamuser
  password: streampassword