apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  SPRING_DATASOURCE_USERNAME: c3RyZWFtdXNlcg==
  SPRING_DATASOURCE_PASSWORD: c3RyZWFtcGFzc3dvcmQ=
  password: c3RyZWFtcGFzc3dvcmQ=