apiVersion: v1
kind: PersistentVolume
metadata:
  name: recordings-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/d/WSL/Recordings   # <- path on your Windows/WSL disk
    type: DirectoryOrCreate


----

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi